/*

Print all subsequences of a string

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, 
that is generated by deleting some character of a given string without changing its order.

Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
*/

function printperm(input, output) {
  if (input.length == 0) {
    console.log(output);
    return;
  }

  printperm(input.substring(1), output + input[0]);
  printperm(input.substring(1), output);
}

var output = "";
var input = "abcd";
printperm(input, output);
